### ISSUE TITLE
Serialization of IDictionary<TKey, TValue> question

### ISSUE THREAD

**Issue by sixlettervariables** [gregsdennis/Manatee.Json#126]
I'm reviewing serialization of various data-structures from our product and found that serializing some `Dictionary<TKey,TValue>` instances with `EncodeDefaultValues = false` produces odd results.

Consider serializing:
```csharp
var states = new Dictionary<string, bool>
{
  { "state-a", true },
  { "state-b", false },
};
```
It becomes (whitespace added for clarity):
```json
{
  "state-a": true,
  "state-b": null
}
```
It seems to me that the 'default' value, w.r.t. dictionaries, would be the dictionary itself rather than the values for keys. It seems that if a key is set, its value should always be serialized. But that value's sub-values--if any--should respect `EncodeDefaultValues`.

That is *almost* the case with `Enum` keyed dictionaries.

Thoughts?

**Comment by gregsdennis** [comment]
`false` goes to `null` because the serializer doesn't serialize default values. You have to turn on `Options.SerializeDefaultValues` to get it to output `false`.

**Comment by sixlettervariables** [comment]
I understand the why for the code at hand, I just wonder if that is the correct behavior given it would not be the same if you serialized:
```csharp
class X
{
  public int A { get; set; }  = 42;
  public bool B { get; set; } = false;
}
```
I get:
```
{
  "A": 42
}
```
And not:
```
{
  "A": 42,
  "B": null
}
```
I see the two cases as being distinctly different:
- An object with a default value for a property
- A non-default dictionary entry with a value that happens to be the default for that type

In the former, it makes sense that you could omit the property, but in the latter the dictionary entry itself is *not* the default value. I would not expect a `null` value unless the value itself was `null`. I *would* expect, however, that if I said to not encode default values, that any sub-values would be omitted as expected.

So:
```csharp
class A
{
   public int X { get; set; }
   public Dictionary<string, bool> Y { get; set; }
   public Dictionary<string, A> Z { get; set; }
}

var a = new A
{
  X = 1,
  Y = new Dictionary<string, bool>
  {
    { "t", true },
    { "f", false }, // ("f", false) != default((string, bool))
  },
  Z = new Dictionary<string, A>
  {
    { "a", null }, // ("a", null) != default((string, A))
    { "b", new A {
        X = 2,
        // Y is the default value for Dictionary<TKey,TValue>
        Z = new Dictionary<string, A> {
          { "c", new A { X = 3 } } // Y and Z are default values
        }
      }
    },
  },
};
```
I would expect the following with `EncodeDefaultValues = false` (`$.Z.b.Y`, `$.Z.b.Z.c.Y`, and `$.Z.b.Z.c.Z` are default values, the rest are not):
```json
{
  "X": 1,
  "Y": {
    "t": true,
    "f": false
  },
  "Z": {
    "a": null,
    "b": {
      "X": 2,
      "Z": {
        "c": {
          "X": 3
        }
      }
    }
  }
}
```
Deeper into the why: we cannot write simple JsonPath queries that tell the difference between truly missing a key in a dictionary and a key with a value of null.

**Comment by gregsdennis** [comment]
I see the difference. I already impose some custom options when serializing a dictionary like that. I can add this to the changes that I make.

**Comment by gregsdennis** [comment]
For progress, please see branch *task/issue-126-dictionary-value-defaults*.

**Comment by gregsdennis** [comment]
@sixlettervariables I've added a few test cases to cover this using the simple example above.  Interestingly, the deserialization tests pass.

**Comment by gregsdennis** [comment]
I think I've been able to make the changes needed to make this work as expected.  Let me know.

If I don't hear anything in a few days, I'll just publish what I have.
