### ISSUE TITLE
[Question] Is it possible to validate JSON object against schema sub-definitions?

### ISSUE THREAD

**Issue by antonGritsenko** [gregsdennis/Manatee.Json#131]
Hi all

Question is in the subject, but let me unwrap what I mean. For instance, let's take the file system sample from http://json-schema.org/example2.html 
We have couple definitions in the schema: diskDevice, diskUUID etc

Is it possible to validate JSON object that represent only the diskDevice against the full schema? Something like 
```
// JSON of diskDeviceObject
{
   "type": "disk",
   "label": "/dev/sd0/vol"
}
```
```
SchemaValidationResults ValidateWithPart(jsonObject, string path)
{
     ...
     schema.Validate(jsonObject, ???);
}

var diskDeviceObject = JsonValue.Parse(...);

var result = ValidateWithPart(diskDeviceObject, "#/definitions/diskDevice");

```

**Comment by gregsdennis** [comment]
Thanks for the question!  I don't support validating against a subschema directly, but I can suggest a few alternatives.

## Acquiring the subschema directly

You could just grab the subschema you want directly out of the schema you have with `schema.Definitions["diskDevice"]`. Then you can validate directly with that.

## Create a ref schema

This involves creating a new schema that will point into a target schema.

So, assuming that the disk schema is at *http://server.com/diskSchema.json*, you'd create another schema like this:

```json
{
  "type" : { "$ref" : "http://server.com/diskSchema.json#/definitions/diskDevice" }
}
```

## Using pointers to extract the schema

If you have the schema in JSON format, you can wait a few days for me to publish my JSON Pointer implementation. Using this, you'll be able to safely extract the portion of the schema you want, parse & deserialize, and then validate using that schema.

**Comment by antonGritsenko** [comment]
Acquiring the subschema directly is perfectly match, thanks a lot!
