### ISSUE TITLE
Extending schemas

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Json#139]
Extending schema vocabularies is currently a discussion topic on the JSON Schema GitHub repo.  Until that is worked out and makes it into a spec, it would be a good idea to have some semblance of extension for the schema classes in this library.

Currently, the schema classes can be subclassed, but validation cannot be overridden.  Extension points need to be made for the schema classes.

**Comment by gregsdennis** [comment]
See branch **feature/139-schema-extensions**.

**Comment by jamlen** [comment]
Is there any wiki or documentation to explain this?

**Comment by gregsdennis** [comment]
@jamlen I don't think I've written anything on this just yet. I believe I have a unit test or two for it.  I'll try to find it and post back here with a link.

**Comment by gregsdennis** [comment]
Please see the following test file for an example.  This is the best I have for now.

https://github.com/gregsdennis/Manatee.Json/blob/master/Manatee.Json.Tests/Schema/SchemaExtensionsTests.cs

**Comment by jamlen** [comment]
Thanks for the quick response!

**Comment by gregsdennis** [comment]
@jamlen if you do end up using this, it's of some interest to the people over at the [JSON Schema spec repo](https://github.com/json-schema-org/json-schema-spec) hope that usage manifests. If you don't mind, would you please keep me informed (my GH username at Yahoo will be fine) on how you're extending them, so that I can inject that use case into the discussion.  It'll really help us get the wording down for when this feature goes into the spec.

Thanks!
