### ISSUE TITLE
Failed to install into project using .Net 4.5.2

### ISSUE THREAD

**Issue by lbcsy** [gregsdennis/Manatee.Json#143]
Could not install package 'Manatee.Json 9.7.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by gregsdennis** [comment]
According to the [.NET Standard docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), .NET Standard 1.3 (which is what Manatee.Json builds to) is only compatible with .NET Framework 4.6+.

**Comment by lbcsy** [comment]
Ok, will try later as I am using Orchard CMS 1.10.1 which is targeting .Net 4.5.2

**Comment by gregsdennis** [comment]
If your app is 4.6, you should have no problem consuming libraries at 4.5.2.

**Comment by gregsdennis** [comment]
@lbcsy were you able to get this going?  Can this issue be closed?

**Comment by lbcsy** [comment]
Please close it, I am not able to try yet as the old Orchard is still in use.

**Comment by gregsdennis** [comment]
Okay.  As I mentioned, you should be able to upgrade your app to .Net 4.6 and still use a 4.5.2 library.  That would allow you to use Manatee.Json.

Let me know if you have further difficulty with this.

**Comment by StefH** [comment]
See also https://github.com/gregsdennis/Manatee.Json/pull/149
