### ISSUE TITLE
Is Yaml validation supported ?

### ISSUE THREAD

**Issue by guy-lud** [gregsdennis/Manatee.Json#144]

**Comment by gregsdennis** [comment]
No. This is a JSON-only library, supporting all things JSON.

Do you have a need for YAML support related to JSON?

**Comment by guy-lud** [comment]
I need to validate a Yaml file could be against Json schema

**Comment by gregsdennis** [comment]
I'm not sure what you mean.  Can you give an example?

**Comment by guy-lud** [comment]
Sure, 
first of all thanks for replying.

I have yaml files with some structure that when given yaml as string i want to verify it against a schema, for structure and type

**Comment by gregsdennis** [comment]
I imagine you're talking about [this] (https://json-schema-everywhere.github.io/yaml).  It's not something I support.

You'd need something to translate the YAML to JSON in order to use this library. This library pears JSON into object models to do everything; it's not dealing directly in text.

**Comment by guy-lud** [comment]
Thanks
