### ISSUE TITLE
Remove StringFormatMethodAttribute from project please

### ISSUE THREAD

**Issue by StefH** [gregsdennis/Manatee.Json#150]
Can you please remove the StringFormatMethodAttribute from the project please and instead add a reference to `JetBrains.Annotations` version 11.1 ? This gives conflicts when another project is using the real JetBrains.Annotations.

Like:

``` xml
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="11.1.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```

**Comment by gregsdennis** [comment]
What is the purpose in this?  I'm trying to avoid external references where possible.

There should be no conflicts.  While it's in the same namespace, it's in a different assembly.

**Comment by StefH** [comment]
There are conflicts.

To solve this the `PrivateAssets` setting is used.

PrivateAssets | These assets will be consumed but won't flow to the parent project (so this means the consumers from your project do not need a reference)

See https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by gregsdennis** [comment]
Will the consumer still be able to utilize the R# functionality provided by this attribute?  That's kinda the purpose in putting it in.

**Comment by StefH** [comment]
Good point. I just tested, and it seems indeed that the consumer cannot see the resharper functionality.

**Comment by gregsdennis** [comment]
I just check the usages of the attribute, and it's just on  exception constructors.  I'll make it internal as it was obviously just for development purposes.

Sorry for the delay.  I'm currently working on another feature and will have a new version out when that's done.
