### ISSUE TITLE
Also support int64 (long) for JsonValue

### ISSUE THREAD

**Issue by StefH** [gregsdennis/Manatee.Json#151]
When assigning a int64 value to JsonValue, I get this error:

`
"Could not cast or convert from System.Int64 to Manatee.Json.JsonValue."} | System.Exception {System.ArgumentException}`

Is it possible to also add implicit conversion from int64?

**Comment by gregsdennis** [comment]
According to [MS](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/implicit-numeric-conversions-table), casting from `long` should work the same as casting from `int`.

I'll create some tests for this.

**Comment by gregsdennis** [comment]
@StefH this works just fine:

	long number = 500;
	JsonValue json = number;

Or were you thinking of something else?  Can you post an example of what you're trying to do?

**Comment by StefH** [comment]
I was trying this:

``` c#
var jobject = ; // This is a Newtonsoft Json object
var jsonValue = new JsonObject(jobject.ToObject<Dictionary<string, JsonValue>>());
```

**Comment by gregsdennis** [comment]
I don't think an implicit cast is going to help you there.

(Maybe I need to create an extension lib that converts from his to mine.)

You might try running it through parsing:

    var parsedJson = JsonValue.Parse(jobject.ToString());

However to do this directly, you'd need some kind of special conversion logic.

**Comment by gregsdennis** [comment]
I created a test:

	var target = new
		{
			LongProp = 500.0,
			stringProp = "hello",
			NestedProp = new
				{
					Culture = "en-nz"
				}
		};

	var jobject = JObject.FromObject(target); // This is a Newtonsoft Json object
	var asDictionary = jobject.ToObject<Dictionary<string, JsonValue>>();
	var jsonValue = new JsonObject(asDictionary);

	Console.WriteLine(jsonValue);

This works, but when I use `500` or `500L`, it doesn't.

**Comment by gregsdennis** [comment]
That said, it doesn't work for the `NestedProp`.  There is no conversion from an anonymous object to `JsonValue`, and it actually just replaces it with null.

So it's looking like you'll still need custom logic.  Or you go through parsing:

	var asString = jobject.ToString();
	var jsonValue = JsonValue.Parse(asString);

**Comment by gregsdennis** [comment]
`explicit`!!!  Making them explicit casts avoids all of the conversion issues.

**Comment by gregsdennis** [comment]
Now I have explicit casts that are complaining about conflicts...
