### ISSUE TITLE
Not intuitive error message when top schema is a $ref

### ISSUE THREAD

**Issue by lbcsy** [gregsdennis/Manatee.Json#194]
Consider a schema like this:
```
{
  "$ref":"#/definitions/apredefinedtype",
  "definitions":{
     "apredefinedtype":{
        ...
      }
  }
}
```
then validation will only point out that there is something wrong in "$ref" if a given Json is invalid to this schema. 

Is it possible to produce more intuitive error message to help the user to locate the actual error location?

**Comment by lbcsy** [comment]
Below is a complete test:
public void Issue194_refNoIntuitiveErrorMessage()
		{
				var serializer = new Manatee.Json.Serialization.JsonSerializer();


				// please review following validation code after creating type is done


				var schemaJson = new JsonObject();
				//schemaJson.Add("$schema", "http://json-schema.org/draft-04/schema#");
				schemaJson.Add("$ref", "#/definitions/apredefinedtype");
				schemaJson.Add("definitions", JsonValue.Parse(
							   @"{
								""apredefinedtype"": {
									""type"": ""object"",
									""properties"": {
										""prop1"": {
											""enum"": [
												""ændring"",
												""test""
											],
											""type"": ""string""
										}
									},
									""required"": [""prop1""]
									}
								}"
							   ));


				var actual = new JsonSchema();
				actual.FromJson(schemaJson, serializer);
				var jObject = JsonValue.Parse("{\"prop11\": \"ændring\", \"prop2\": {\"prop3\": \"ændring\"}}");
				var messages = actual.Validate(jObject);
				messages.AssertValid();
			
		}
	
How do I get the actual error message of something like "prop1 is required"? So far the validate result messages only has "$ref" in it, below is the messages in Json:
{\"IsValid\":false,\"RelativeLocation\":[\"$ref\"],\"AbsoluteLocation\":null,\"InstanceLocation\":[],\"AnnotationValue\":null,\"Keyword\":\"$ref\",\"AdditionalInfo\":{},\"NestedResults\":[]}

**Comment by gregsdennis** [comment]
With the rework of the JSON Schema implementation, I've left out the error messages in favor of identifying the keyword that failed.  In this way, the you can easily identify the keyword that caused the problem and supply your own error message that is customized for your users.

That said, it looks like identifying the keyword isn't working, so I'll have a look at that.

**Comment by gregsdennis** [comment]
Okay... The `$ref` keywords wasn't attaching its nested results to the results object it returned.  I've fixed that and I'm getting this now:

```json
{
  "valid" : false,
  "keywordLocation" : "#/$ref/required",
  "instanceLocation" : "#",
  "keyword" : "required",
  "additionalInfo" : {
      "missing" : [
          "prop1"
        ]
    }
}

```

**Comment by lbcsy** [comment]
Great, that is quick!
Can't wait to see it available in NuGet.

**Comment by gregsdennis** [comment]
https://www.nuget.org/packages/Manatee.Json/

Version 10.0.5 contains your fix.

**Comment by gregsdennis** [comment]
There's still a problem in there... it's missing the `absoluteLocation` which should point directly to the property through the definition.

**Comment by gregsdennis** [comment]
Okay.  It only does that if you define a base URI (like in the `$id` property).  Otherwise, it can't create an absolute URI.

Even so, when adding the `$id`, it didn't build the absolute URI correctly, so I'll be updating that soon.

**Comment by gregsdennis** [comment]
@lbcsy version 10.1.0 fixes an issue with rendering the absolute URI.
