### ISSUE TITLE
Adjacent escapes incorrectly throw JsonSyntaxException: Invalid UTF-32 code point

### ISSUE THREAD

**Issue by DavidSimner** [gregsdennis/Manatee.Json#203]
With `Manatee.Json` version `10.1.2` there is a bug that adjacent escapes incorrectly throw a `JsonSyntaxException` with the message `Invalid UTF-32 code point`

For example, deserializing the JSON `{ "myKey": "Hello\u003c\u003eWorld" }` will throw a `Manatee.Json.JsonSyntaxException` with the message `Invalid UTF-32 code point. Path: '/myKey'`

The following code demonstrates this bug, and it also demonstrates that alternative JSON deserializers handle this case just fine.

In particular, the C# code:
```
public static class Program {
        private const string Json = @"{ ""myKey"": ""Hello\u003c\u003eWorld"" }";

        public static void Main() {
            Console.WriteLine($"JSON input is  {Json}");
            Console.WriteLine();

            UseDotNetFramework();

            UseNewtonsoftJsonDotNet();

            UseManateeDotJson();
        }

        private static void UseDotNetFramework() {
            Console.WriteLine("Using .NET Framework JSON Deserializer:");
            var javaScriptSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            var deserialized = javaScriptSerializer.Deserialize<Dictionary<string, string>>(Json);
            Console.WriteLine(deserialized["myKey"]);
            Console.WriteLine();
        }

        private static void UseNewtonsoftJsonDotNet() {
            Console.WriteLine("Using Newtonsoft.Json Deserializer:");
            var deserialized = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, string>>(Json);
            Console.WriteLine(deserialized["myKey"]);
            Console.WriteLine();
        }

        private static void UseManateeDotJson() {
            Console.WriteLine("Using Manatee.Json Deserializer:");
            var value = Manatee.Json.JsonValue.Parse(Json);
            var jsonSerializer = new Manatee.Json.Serialization.JsonSerializer();
            var deserialized = jsonSerializer.Deserialize<Dictionary<string, string>>(value);
            Console.WriteLine(deserialized["myKey"]);
            Console.WriteLine();
        }
    }
```

To compile the above code you will need to add references to:
- A NuGet reference to `Manatee.Json`
- A NuGet reference to `Newtonsoft.Json`
- A reference to the framework assembly `System.Web.Extensions.dll`

When run, the above code currently produces the console output:
```
JSON input is  { "myKey": "Hello\u003c\u003eWorld" }

Using .NET Framework JSON Deserializer:
Hello<>World

Using Newtonsoft.Json Deserializer:
Hello<>World

Using Manatee.Json Deserializer:

Unhandled Exception: Manatee.Json.JsonSyntaxException: Invalid UTF-32 code point. Path: '/myKey'
   at Manatee.Json.Parsing.JsonParser.Parse(String source)
   at Manatee.Json.JsonValue.Parse(String source)
   at ConsoleApp5.Program.UseManateeDotJson() in Program.cs:line 37
   at ConsoleApp5.Program.Main() in Program.cs:line 17
Press any key to continue . . .
```

Please can you fix the `JsonParser` to handle this situation so that it gives the same output as the other JSON deserializers.

**Comment by gregsdennis** [comment]
Thanks for the report and the investigation.  I'll work up a fix and have it out as soon as I can.

**Comment by gregsdennis** [comment]
I'll add your test case to the list here:

https://github.com/gregsdennis/Manatee.Json/blob/master/Manatee.Json.Tests/JsonValueParseTest.cs

But if you'll notice, I actually have a case where I have two consecutive double-escapes on line 37.  I wonder what the difference is.

**Comment by gregsdennis** [comment]
Oh! I think I see it. The parser thinks that the consecutive escapes are part of a single Unicode pair rather than two individual code points.  That's why it's saying it's invalid.

I can make adjustments to only check for a pair if the first code is within the right range.

**Comment by gregsdennis** [comment]
@DavidSimner, please see v10.1.3.  thanks again for the report.
