### ISSUE TITLE
PropertiesKeyword does not return nestedResults

### ISSUE THREAD

**Issue by Iblis** [gregsdennis/Manatee.Json#209]
I don't know if this is intended, but the PropertiesKeyword fills the nestedResults only in case of errors/invalid results. To be honest, this looks more like a regression introduced when Manatee.Json moved from SchemaValidationError to SchemaValidationResults. 
https://github.com/gregsdennis/Manatee.Json/blob/d6e3b02c5212e14317d00180f66080393e6da477/Manatee.Json/Schema/Keywords/PropertiesKeyword.cs#L59

The AdditionalPropertiesKeyword does not filter the results like that, and for my use case it would be valuable to have access to the nestedResults of the properties Keyword in the overall SchemaValidationResults.

If this is indeed a regression, I can also provide a PR if requested.

**Comment by gregsdennis** [comment]
Yeah I think I fixed that in my schema draft 8 branch. Thank for reporting. That should release in the next couple weeks (just waiting on the spec to release). If you need it sooner, let me know.

**Comment by Iblis** [comment]
Good to hear that! Being able to already make use of it, eg. via Prerelease-NuGet package would be nice. The functionality I want to implement right now is to detect which subschema of an "oneOf"-declaration was found to be valid. And I don't see any other way than checking the SchemaValidationResults for that.

**Comment by gregsdennis** [comment]
That's a good idea.  I'll work up the release notes and put out a prerelease.

**Comment by gregsdennis** [comment]
@Iblis released 10.2.0-beta1.

**Comment by Iblis** [comment]
Great, thanks a lot! This solved not just this issue, but also an issue I had with $refs! The $ref keyword previously would use the context's local id when it should have used the documentPath. The old behaviour is now configureable via a RefResolutionStrategy. Nice!
