### ISSUE TITLE
JSON Schema validation fails or hangs against large schema file

### ISSUE THREAD

**Issue by NitinM3** [gregsdennis/Manatee.Json#218]
When i try to validate json object against large JSON Schema, it fails or rather keep on processing for unlimited time. See attached schema and sample json object

[Sample.zip](https://github.com/gregsdennis/Manatee.Json/files/3400597/Sample.zip)

```c#
public class SchemaValidator
    {
        private JsonSchema schema;
        private Stopwatch stopwatch;

        public SchemaValidator()
        {
            stopwatch = new Stopwatch();
            stopwatch.Start();
            var serializer = new JsonSerializer();
            var text = File.ReadAllText("fhir.schema.json");        
            var json = JsonValue.Parse(text);
            schema = serializer.Deserialize<JsonSchema>(json);
            stopwatch.Stop();

            Console.WriteLine($"Time Taken to load Schema : {stopwatch.ElapsedMilliseconds}");
        }

        public void Validate()
        {
            var result = schema.ValidateSchema();
            //if (result.IsValid)
            {
               var text = File.ReadAllText("Sample.json");
                var payload = JsonValue.Parse(text);
                stopwatch.Start();
                var validationResult = schema.Validate(payload);
                stopwatch.Stop();
                Console.WriteLine($"Time Taken to validate payload : {stopwatch.ElapsedMilliseconds}");
            }
        }
    }
```

**Comment by gregsdennis** [comment]
Thanks for reporting and for putting Mandate.Json through its paces.  I'll have a look and report back. There's likely some optimizations that could be made.

**Comment by gregsdennis** [comment]
Some initial observations:

- Using a `List<string>` to track evaluated properties probably isn't the best of ideas.  I paused the process and checked this property, and it had... over 13M items.  I know there weren't that many unique properties, so... `HashSet<string>` it is!
- I need logging in here somewhere.

**Comment by gregsdennis** [comment]
How long have you let it run?

**Comment by NitinM3** [comment]
Application was running more than a hour, then i closed forcefully.

**Comment by gregsdennis** [comment]
Yeah, I just let it run for about an hour and a half.  Same result (none).

There were two other fine folk who have schema implementations in C++, who each ran it under theirs and it took ~25 minutes to run for each of them.

So, while I *do* have some optimizations to do, there is something very horrible with this schema (besides it being so large).  Have you run it with any other implementations with better results?

**Comment by NitinM3** [comment]
Yes. I ran against newtonsoft json schema. It took few miliseconds.

**Comment by gregsdennis** [comment]
And did it pass? The other implementations reported errors.

**Comment by NitinM3** [comment]
Validation errors reported since json object is not valid as per schema. But in the case of Manatee json, validation itself takes lot of time. It was running even after waiting for 1 hour.

**Comment by gregsdennis** [comment]
It's probably a difference of opinion, but `JSON is valid against no schemas from 'oneOf'. Path '', line 1, position 1.` is not really an error.  Yes, it returned that the instance isn't valid, but it contains no information as to why it failed every subschema in the `oneOf`.  Mine is trying to compile all of that information together.

**Comment by NitinM3** [comment]
Tried setting `JsonSchemaOptions.OutputFormat = SchemaValidationOutputFormat.Basic;` but no luck.  Am i missing something?


`public SchemaValidator()
        {
            stopwatch = new Stopwatch();
            JsonSchemaOptions.OutputFormat = SchemaValidationOutputFormat.Basic;
            stopwatch.Start();
            var serializer = new JsonSerializer();
            var text = File.ReadAllText("fhir.schema.json");
            var json = JsonValue.Parse(text);
            schema = serializer.Deserialize<JsonSchema>(json);
            stopwatch.Stop();
            Console.WriteLine($"Time Taken to load Schema : {stopwatch.ElapsedMilliseconds}");
        }`

**Comment by gregsdennis** [comment]
Not Basic, Flag.

**Comment by NitinM3** [comment]
I don't see Flag as option in `SchemaValidationOutputFormat.` Do i need to update package? Currently using `10.1.3`.

**Comment by gregsdennis** [comment]
Oh.  I thought you were using the v11 beta.  That has the `Flag` setting.  I'm still looking to use this schema to increase performance, but I can't do anything else.  It looks like your solutions are to get the v11 beta (which really is quite stable; I'm just waiting for the draft 8 schema spec to release) or use Newtonsoft.

**Comment by gregsdennis** [comment]
So it looks like the issue is collecting all of the errors.  There's just a lot due to the size of the schema.  The structure of the output is based on the structure of the schema, so the larger and more complex the schema is (yours is immense and references into itself in lots of loopy ways), the larger the output will be.  Just to give you an idea of the size, I removed all except the `Account` reference from `#/definitions/ResourceList/oneOf`, and it took 27 seconds to complete... with a result that was over 316K lines long.

It's trying to build up this result object that's causing the pain.  It's eating up the machine's memory like candy, and eventually the machine runs out, which then slows down the validation as the OS has to page the memory.
