### ISSUE TITLE
Ability to auto-serialise and deserialise immutable types

### ISSUE THREAD

**Issue by bluebear94** [gregsdennis/Manatee.Json#222]
Right now, I have a `struct` with a number of immutable fields which I'd like to have Manatee.Json serialise and deserialise automatically. However, in order to do that, I need to make each field immutable, as well as add a parameterless constructor (and make my type a `class`, or alternatively create and register a resolver). It would be better to be able to specify a constructor to call during deserialisation.

Of course, it is possible to implement `ISerializer` for each type I need to do this for, but doing so would be tedious.

**Comment by gregsdennis** [comment]
I think I played around with this a couple years ago, but I can try it again.  It could take a bit.  In the meantime, I suggest the resolver method.

**Comment by gregsdennis** [comment]
@bluebear94 I have a PR available.  It'll be in v11.0.0-beta7.  I'd do a minor release on the current v10, but there were breaking changes in this fix anyway, though probably nothing that'll affect you.
