### ISSUE TITLE
Any chance this code compiles on Mono/OSX ?

### ISSUE THREAD

**Issue by Asc2011** [gregsdennis/Manatee.Json#229]
i just found out that this project supports the 09-2019 a.k.a 'Draft-8'-Version and seems to be the only alternative to AJV, at the moment. 

just curious if it might compile on Mono/OSX ?

**Comment by gregsdennis** [comment]
It's a netstandard2.0 library, so it should just work there.

**Comment by Asc2011** [comment]
great, i'll try it out.

**Comment by gregsdennis** [comment]
@Asc2011 Just confirmed that you can download the nuget package and use it as is on Mac.
