### ISSUE TITLE
Replacing $ref paths with resolved objects

### ISSUE THREAD

**Issue by SamuelDev** [gregsdennis/Manatee.Json#230]
Hey so we are using Manatee for our Json Schema validation, and ran into wanting to do something that I dont think is currently possible (maybe it is? Let me know!)

We store our JSON schema files as strings into our database, then when json objects are later loaded into the system, we pull out the schemas, and validate the objects being loaded.

This currently works because all references to different types are currently kept in the same file as the schema, and referenced via ("$ref": "#/definitions/myInternalDefinition"). This is handy because no external references need to be resolved after the database call (which dont exist because it's coming from a DB, not a file).

However we now want to store some of these definitions externally from the given schema file, and reference them via ("$ref": "definitions.json#/definitions/myExternalDefinition").  We need some way to basically replace this reference with the actual json object definition, since we won't have access to the original files later on when we read the schema string out of the database.

Hopefully something like this is already possible, but I didn't stumble into anything after playing around with it for awhile.

**Comment by gregsdennis** [comment]
Hey, @SamuelDev! Thanks for using Manatee.Json!

This is absolutely a thing you can do. I actually do something similar in the schema test suite.

Have a look at the [test suite](https://github.com/gregsdennis/Manatee.Json/blob/master/Manatee.Json.Tests/Schema/TestSuite/JsonSchemaTestSuite.cs) line 70.  You'll see here that I'm setting the `JsonSchemaOptions.Download` property to a new `Func`.  Overwrite this to look into your database, and you should be good to go.

One note, though: if you still it need to resolve internet references, you may want to hold onto the properties default value and fall back to calling that inside your func.

**Comment by gregsdennis** [comment]
@SamuelDev does this answer your question?

**Comment by SamuelDev** [comment]
Hey, yeah we implemented something similar and it is working for us.

**Comment by gregsdennis** [comment]
Awesome. Thanks.  Closing the issue.
