### ISSUE TITLE
SchemaReferenceNotFoundException on valid refs in Schema

### ISSUE THREAD

**Issue by ArneKlein** [gregsdennis/Manatee.Json#231]
**Describe the bug**
We have created a schema with a lot of definitions all of which have an $id. When creating a reference from one definition to the next, an exception is returned.

Example Schema:
`{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://localhost/Resistance.schema.json",
    "type": "object",
    "definitions": {
        "1DVector": {
            "$id": "#1DVector",
            "type": "array",
            "minItems": 1,
            "items": {
                "anyOf": [
                    {
                        "type": "number"
                    },
                    {
                        "type": "null"
                    }
                ],
                "default": null,
                "examples": [
                    1.1,
                    2.3,
                    4.5
                ]
            }
        },
        "t_PulseTimePeriod": {
            "$id": "#t_PulseTimePeriod",
            "type": "object",
            "title": "The t_PulseTimePeriod Schema",
            "required": [
                "values"
            ],
            "properties": {
                "values": {
                    "$ref": "#/definitions/1DVector"
                }
            }
        }
    },
    "required": [
        "t_PulseTimePeriod"
    ],
    "properties": {
        "t_PulseTimePeriod":
        {
            "$ref": "#t_PulseTimePeriod"
        }
    },
    "additionalProperties": false
}`

Example JSON:
```
{
  "t_PulseTimePeriod": {
    "values": []
  }
}
```
  
Note: Replacing the $ref in t_PulseTimePeriod  to 1DVector with #1DVector leads to a NullReferenceException instead. Both variants work in https://www.jsonschemavalidator.net/

**Expected behavior**
Validation exception is thrown: 
1. Array item count 0 is less than minimum count of 1.

**Desktop (please complete the following information):**
 - Windows 10
- .Net Target 4.7.1
 - packages\Manatee.Json.11.0.1\lib\netstandard2.0\Manatee.Json.dll

**Comment by gregsdennis** [comment]
Thanks for reporting this.  References are hard.

FYI - This behavior changes with draft 2019-09.  This usage of `$id` is no longer allowed and replaced by `$anchor`.  Additionally, the value no longer uses a `#`.

**Comment by ArneKlein** [comment]
Woah! Thank you for that fast response!

Yeah I bet that. Does this change affect the behavior of the refs as well?

**Comment by gregsdennis** [comment]
Not really.  It just changes how portions of the documents are identified.  The ref essentially works the same.

**Comment by gregsdennis** [comment]
I think I've replicated what you're seeing with a unit test using the above schema and instance.  I can dig into the issue now.  Thanks for the detailed report.

Here's the error I get: `Cannot resolve schema referenced at '#/properties/t_PulseTimePeriod'.`

**Comment by gregsdennis** [comment]
Once I got past the NRE, I was able to replicate your schema not found error.  A fix is coming soon.
