### ISSUE TITLE
Non helpful error System.AggregateException on invalid paths in $refs

### ISSUE THREAD

**Issue by ArneKlein** [gregsdennis/Manatee.Json#232]
**Feature Request**
We have to schema files where one references the other:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://localhost/Resistance.schema.json",
    "type": "object",
    "required": [
        "t_PulseTimePeriod"
    ],
    "properties": {
        "t_PulseTimePeriod":
        {
            "$ref": "./definitions.schema.json#definitions/t_PulseTimePeriod"
        }
    },
    "additionalProperties": false
}
```

and 

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://localhost/definitions.schema.json",
    "definitions": {
        "t_PulseTimePeriod": {
            "type": "object",
            "title": "The t_PulseTimePeriod Schema",
            "required": [
                "values"
            ],
            "properties": {
                "variableName": {
                    "type": "string",
                    "const": "t_PulseTimePeriod"
                }
            }
        }
    }
}
```

**To Reproduce**
Place both files in any folder next to each other outside of the project.
Now when first reading the schema as text, e.g.:
```
var schemaText = File.ReadAllText("c:\schema.json");
var schemaJson = JsonValue.Parse(schemaText);
var schema = new JsonSerializer().Deserialize<IJsonSchema>(schemaJson);
```
 Manatee.Json loses the context (as expected) and can't resolve the path to the second schema. This lead to an System.AggregateException telling me, at least one error occured. 

**Expected behavior**
An exception telling me, which reference could not be resolved and where Manatee.Json was looking for the reference.

**System information:**
Windows 10
.Net Target 4.7.1
packages\Manatee.Json.11.0.1\lib\netstandard2.0\Manatee.Json.dll

**Comment by gregsdennis** [comment]
The AggregateException is likely from trying to download from `http://localhost/`.

If you were to load and deserialize *both* schemas (before attempting to validate), it would register both schemas with `JsonSchemaRegistry` under the respective `$id`s and should then be able to resolve them.

**Comment by gregsdennis** [comment]
Looks like I need to document that better.  There's a brief mention of it [here](https://gregsdennis.github.io/Manatee.Json/usage/schema/v9.html#references), but that's for an older version, and not quite visible.

**Comment by ArneKlein** [comment]
Yes, I missed that part in the documentation. I did find the solution myself, however, I found the message is not that helpful. 

Now I encountered another issue after registering only one schema, that the $refs in the second schema don't work. 

Unfortunatly registering both didn't help either.

This might be due the fact, that neither schema can actually be resolved by its URL at the moment, only by the relative paths.

**Comment by gregsdennis** [comment]
Hm... once registered, the registry should see them and not try to download them.  I'll set up a test for it.

**Comment by ArneKlein** [comment]
I have found the problem I think, once registered the refs within the schema are always resolved against the path in the ID e.g.:
a ref like this `"$ref": "#/definitions/TemplateElement"` in a schema with the ID "$id": "http://localhost/eq/V3/dsm/dsm_template.schema.json", is resolved against http://localhost/eq/V3/dsm/dsm_template.schema.json#/definitions/TemplateElement 

This error can also be reproduced with just a single schema.

**Comment by gregsdennis** [comment]
No need. Thanks

**Comment by gregsdennis** [comment]
So it looks like I have it set up to register the schema when it's used to validate something.  So if you use `resistance` to validate something, and you haven't used `definitions` yet (why would you validate something with that?), then it'll fail because `definitions` isn't registered.

However, if you explicitly register them both, it works.

Here's my test:

```c#
[Test]
public void Issue232_RefsNotResolvedAgainstId()
{
    var resistanceSchema = new JsonSchema()
        .Schema(MetaSchemas.Draft07.Id)
        .Id("http://localhost/Resistance.schema.json")
        .Type(JsonSchemaType.Object)
        .Required("t_PulseTimePeriod")
        .Property("t_PulseTimePeriod", new JsonSchema().Ref("./definitions.schema.json#definitions/t_PulseTimePeriod"))
        .AdditionalProperties(false);
    var definitionsSchema = new JsonSchema()
        .Schema(MetaSchemas.Draft07.Id)
        .Id("http://localhost/definitions.schema.json")
        .Definition("1DVector", new JsonSchema()
                        .Id("#1DVector")
                        .Type(JsonSchemaType.Array)
                        .MinItems(1)
                        .Items(new JsonSchema()
                                    .AnyOf(new JsonSchema().Type(JsonSchemaType.Number),
                                            new JsonSchema().Type(JsonSchemaType.Null))
                                    .Default(JsonValue.Null))
                        .Examples(1.1, 2.3, 4.5))
        .Definition("t_PulseTimePeriod", new JsonSchema()
                        .Id("#t_PulseTimePeriod")
                        .Type(JsonSchemaType.Object)
                        .Title("The t_PulseTimePeriod Schema")
                        .Required("values")
                        .Property("values", new JsonSchema().Ref("#/definitions/1DVector")));

    // this is the part you need.
    JsonSchemaRegistry.Register(resistanceSchema);
    JsonSchemaRegistry.Register(definitionsSchema);

    var instance = new JsonObject { ["t_PulseTimePeriod"] = new JsonObject { ["values"] = new JsonArray() } };

    var format = JsonSchemaOptions.OutputFormat;
    try
    {
        JsonSchemaOptions.OutputFormat = SchemaValidationOutputFormat.Detailed;
        var result = resistanceSchema.Validate(instance);

        result.AssertInvalid();
    }
    finally
    {
        JsonSchemaOptions.OutputFormat = format;
    }
}
```

**Comment by gregsdennis** [comment]
Secondarily, while this works, I'd suggest you organize a bit differently.  Instead of having a single schema file to hold all of your definitions, just store each definition in a separate file and reference them accordingly.  It'll make your references shorter, too.

**Comment by gregsdennis** [comment]
@ArneKlein I'd love to get your feedback on the added docs.  You can see them on the PR (linked above).

**Comment by gregsdennis** [comment]
Since the PR basically adds a test and docs (that can easily be changed) I'm going to go ahead and merge it, closing this issue.
