### ISSUE TITLE
Debug logging around schema decision making process

### ISSUE THREAD

**Issue by Relequestual** [gregsdennis/Manatee.Json#237]
I'd like to be able to see logs of what the library did. What steps did it take? Why did it not evaluate x? Why did it decide that y was invalid?

As per discussed on slack, filing an issue =]

**Comment by gregsdennis** [comment]
I have ideas... the question is: are any of them good?

**Comment by gregsdennis** [comment]
Partial implementation: see https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues/291
