### ISSUE TITLE
json-schema official test suite

### ISSUE THREAD

**Issue by jruizaranguren** [gregsdennis/Manatee.Json#24]
Hi,

I have not found in the docs any reference to the [Json-Schema official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite). In order to be considered a full-fledged alternative to Json.Net schema this seems an unavoidable requirement.

Is it in your roadmap or this project is frozen now? 
Best regards, and congrats for your work.

**Comment by gregsdennis** [comment]
I don't know that it's a *requirement* for JSON Schema.  The project ReadMe opens with,

>This repository contains a set of JSON objects that implementors of JSON Schema validation libraries can use to test their validators.

Even so, I see your point as far as implementing it to solidify this library as an alternative for Json.Net. I'll take this as a suggestion and work to implement this in the tests.

---

No, this project is not frozen.  While I feel that it is fairly mature, I haven't stopped supporting it.  Every now and then bugs arise from my own use as well as others.  New development *has* slowed, however, as I find ideas lacking.  (I usually have to conceive of them myself.)

**Comment by jruizaranguren** [comment]
Yes, `requirement` was used with a conditional. It is not an official requirement. But I guess it would make easier to add your library to the [`official` implementation tools list.](http://json-schema.org/implementations.html)
A first approach to implementation can be quite straightforward with data-driven tests, only one method to load the tests and another one to check the validation.

**Comment by gregsdennis** [comment]
Just downloaded.   I think you found me some work. :smile: 

I'll leave this open until the suite passes.

**Comment by jruizaranguren** [comment]
Great. Let me know if I can help in some way (comfortable in c# and json-schema).

**Comment by gregsdennis** [comment]
For now, I'm just trying to get the tests set up.  I can see some potential difficulties around some of the more advanced remote ref scenarios.

But, alas... I need sleep.

**Comment by gregsdennis** [comment]
Already found a couple time issues (#25 & #26) as well as a host of others I haven't investigated yet.

Thanks for this.

**Comment by gregsdennis** [comment]
@jruizaranguren need your opinion.  One of the test sets uses the schema

    {
        "items": [{}],
        "additionalItems": {"type": "integer"}
    }

Does this test _imply_ that it's describing an array?

**Comment by jruizaranguren** [comment]
It doesn't.
The target can be an object. In that case, `items` and `additionalItems` are ignored and it should be validated.

**Comment by gregsdennis** [comment]
I get it.  They only apply in the case that the value *is* an array.

Also, I noticed that there's not actually a `format` property defined in the schema.  Does this seem odd?

**Comment by jruizaranguren** [comment]
I'm not sure what is the use of `format` your are thinking on, but [there exists a `format` keyword in `jsonschema`](http://json-schema.org/latest/json-schema-validation.html#anchor104)

**Comment by gregsdennis** [comment]
Right, the keyword exists, but it's not listed as a property in draft-04.  It's used as one several times, though.

**Comment by gregsdennis** [comment]
@jruizaranguren, I have it to the point where I'm only failing 6 tests, 3 of which are reference path escape tests.  But I can't find anything about reference escaping in the spec.

Given the examples, I understand the need for the slash and tilde escape, but I don't get the percent escape.

**Comment by jruizaranguren** [comment]
JSON Schema uses [JSON Reference](https://tools.ietf.org/id/draft-pbryan-zyp-json-ref-03.html) as a mechanism for schema addressing.

**Comment by gregsdennis** [comment]
How did you find that?!

**Comment by jruizaranguren** [comment]
Everything is [in the docs](http://json-schema.org/latest/json-schema-core.html) :smile:

**Comment by gregsdennis** [comment]
All tests passing.  Will be posting v5.0.0 soon to include these changes.
