### ISSUE TITLE
No validation error messages

### ISSUE THREAD

**Issue by kentcb** [gregsdennis/Manatee.Json#245]
**Describe the bug**
This is likely a user error, since I'm only just starting to use this library. However, I'm finding that schema validation works in the sense that `IsValid` is set to the expected value, but I don't get any error messages when `IsValid` is `false`.

**To Reproduce**
```C#
var schema = JsonSchemaRegistry.Get("file://C:/Users/Kent/schema..json");
var input = "{ \"foo\": 42 }";
var inputJson = JsonValue.Parse(input);

schema.ValidateSchema();
var result = schema.Validate(inputJson);
result.Dump();
```

Where `schema.json` contains:

```json
{
    "$id": "https://example.com/address.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "An address similar to http://microformats.org/wiki/h-card",
    "type": "object",
    "properties": {
        "post-office-box": {
            "type": "string"
        },
        "extended-address": {
            "type": "string"
        },
        "street-address": {
            "type": "string"
        },
        "locality": {
            "type": "string"
        },
        "region": {
            "type": "string"
        },
        "postal-code": {
            "type": "string"
        },
        "country-name": {
            "type": "string"
        }
    },
    "required": [
        "locality",
        "region",
        "country-name"
    ],
    "dependencies": {
        "post-office-box": [
            "street-address"
        ],
        "extended-address": [
            "street-address"
        ]
    }
}
```

The result is:

![image](https://user-images.githubusercontent.com/1901832/72520951-431e3080-38a6-11ea-8863-5d36f7ccd604.png)

**Expected behavior**
I am expecting `ErrorMessage` and probably `AdditionalInfo` to be populated. Maybe `NestedResults` too.

**Desktop (please complete the following information):**
 - OS: Windows
- .NET Target: netstandard 2.0
 - Version: `12.0.2`

**Comment by gregsdennis** [comment]
It sounds like you haven't changed the default output setting which defaults to `flag`, a simple pass/fail indicator.  See https://gregsdennis.github.io/Manatee.Json/usage/schema/validation.html#validation-results for details.

**Comment by kentcb** [comment]
@gregsdennis Thanks, that was it. I figured this was a PEBKAC issue!
