### ISSUE TITLE
Logging takes a lot of time even when disabled.

### ISSUE THREAD

**Issue by idstam** [gregsdennis/Manatee.Json#257]
Even though JsonOptions.LogCategory is set to None a lot of time is spent for the Log functions.

I removed all calls to Log.Schema and saved about 30% in runtime when validating a large message against aschema compared to setting LogCategory to None.

I think this is because there are a lot of string processing to build the parameters that are sent to the logging even though they will not be used when LogCategory is None.

Sadly I think the solution to that would be to sprinkle the code with if statements encapsulating the calls to the Log functions.

**Comment by gregsdennis** [comment]
Have you tried setting `JsonSchema.Log` to null?  That _should_ ignore the logging calls (unless my understanding of `Log?.Schema(<string processing>)` is wrong, which it may be).

**Comment by gregsdennis** [comment]
Yeah... this test fails, meaning that the string arg isn't processed at all.

```c#
[Test]
public void NoLogTest()
{
    int storedValue = 0;

    int PrintValue(int value)
    {
        storedValue = value;
        return value;
    }

    JsonOptions.Log = null;
    JsonOptions.Log?.Verbose($"changing storedValue to {PrintValue(4)}");

    Assert.AreEqual(4, storedValue);
}
```

**Comment by idstam** [comment]
Setting `JsonOptions.Log` to null doesn't help.

I.E. his call: `Log.Schema($"Begin validation of {context.InstanceLocation} by {context.RelativeLocation}");`

will process the string before it is actually used in the Log.Schema metod where the suggested null will help.

With a release build my test takes about 18 seconds whether or not I set it to null, but if I have if statements around all log calls it takes about 14 seconds. 
_(The difference was larger with a debug build.)_

**Comment by gregsdennis** [comment]
Ah... it's because of the extension method.  The argument is evaluated because it's being passed to an extension method that ultimately does nothing with it.  Got it.

**Comment by gregsdennis** [comment]
Please see v12.3.0 for the fix.
