### ISSUE TITLE
JsonSchemaOptions_BasicDownload writes to Console

### ISSUE THREAD

**Issue by reardonj** [gregsdennis/Manatee.Json#263]
When calling JsonSchemaRegistry.Get() I see the path to the schema written to the application's console output. This appears to be caused by JsonSchemaOptions._BasicDownload, which has a call to Console.WriteLine on its first line.

**Expected behavior**
I expect no output to be written to the console.

**Comment by gregsdennis** [comment]
Might have a leftover from debugging.  Thanks for catching it.  I'll replace that with a logging line.

**Comment by gregsdennis** [comment]
This is resolved in v13
