### ISSUE TITLE
JsonSerializer does not honor the Options property

### ISSUE THREAD

**Issue by svenskmand** [gregsdennis/Manatee.Json#265]
**Describe the bug**
The `Manatee.Json.Serialization.JsonSerializer` does not honor the configuration in the `Options` property.

**To Reproduce**
```cs
[Fact]
public void TestDateTimeCustomFormatToJson() {
	var date = new System.DateTime(1989, 4, 16, 13, 11, 20, 721, DateTimeKind.Utc);
	var serializer = new Manatee.Json.Serialization.JsonSerializer();
	// serializer.Options.DateTimeSerializationFormat = Manatee.Json.Serialization.DateTimeSerializationFormat.Iso8601;
	serializer.Options.CustomDateTimeSerializationFormat = "yyyy-MM-ddTHH:mm:ss.fffzzz";
	var actual = serializer.Serialize<System.DateTime>(date).ToString();
	var expected = "\"1989-04-16T13:11:20.721+00:00\"";
	Assert.Equal(expected, actual);
}


[Fact]
public void TestDateTimeCustomFormatFromJson() {
	var serializer = new Manatee.Json.Serialization.JsonSerializer();
	// serializer.Options.DateTimeSerializationFormat = Manatee.Json.Serialization.DateTimeSerializationFormat.Iso8601;
	serializer.Options.CustomDateTimeSerializationFormat = "yyyy-MM-ddTHH:mm:ss.fffzzz";

	var actual = serializer.Deserialize<System.DateTime>(
		Manatee.Json.JsonValue.Parse("\"1989-04-16T13:11:20.721+00:00\""));
	var expected = new System.DateTime(1989, 4, 16, 13, 11, 20, 721, DateTimeKind.Utc);
	Assert.Equal(expected.ToString(), actual.ToString());
}
```

**Expected behavior**
The dates where expected to follow the format specified.

**Desktop (please complete the following information):**
 - OS: Windows 10
- .Net Target Core 
 - Version 3.0

**Additional context**

**Comment by gregsdennis** [comment]
You need to set

```c#
serializer.Options.DateTimeSerializationFormat = DateTimeSerializationFormat.Custom
```

Granted, the remark on that property "If a custom serializer for DateTime has been registered, this property will have no effect." isn't worded in the best way.

**Comment by svenskmand** [comment]
> You need to set
> 
> ```cs
> serializer.Options.DateTimeSerializationFormat = DateTimeSerializationFormat.Custom;
> ```
> 
> I can update the property to auto-set the format to custom when a custom format is set as well.

Ok, thanks, now I got it working :) Yes that is probably a good idea :)

I have another question though, if I instead of `Cusom` I choose `Iso8601` I would expect the output to be the same, according to your documentation:
> // Summary:
> //     Output conforms to ISO 8601 formatting: YYYY-MM-DDThh:mm:ss.sTZD (e.g. 1997-07-16T19:20:30.45+01:00)

But the following tests fail even though they follow the format specified above.
```cs
[Fact]
public void TestDateTimeCustomFormatToJson() {
	var date = new System.DateTime(1989, 4, 16, 13, 11, 20, 721, DateTimeKind.Utc);
	var serializer = new Manatee.Json.Serialization.JsonSerializer();
	serializer.Options.DateTimeSerializationFormat = Manatee.Json.Serialization.DateTimeSerializationFormat.Iso8601;

	var actual = serializer.Serialize<System.DateTime>(date).ToString();
	var expected = "\"1989-04-16T13:11:20.721+00:00\"";
	Assert.Equal(expected, actual);
}

[Fact]
public void TestDateTimeCustomFormatFromJson() {
	var serializer = new Manatee.Json.Serialization.JsonSerializer();
	serializer.Options.DateTimeSerializationFormat = Manatee.Json.Serialization.DateTimeSerializationFormat.Iso8601;

	var actual = serializer.Deserialize<System.DateTime>(
		Manatee.Json.JsonValue.Parse("\"1989-04-16T13:11:20.721+00:00\"")).ToUniversalTime();
	var expected = new System.DateTime(1989, 4, 16, 13, 11, 20, 721, DateTimeKind.Utc);
	Assert.Equal(expected.ToString(), actual.ToString());
}
```

**Comment by gregsdennis** [comment]
Hm... looks like I have tests for the other formats, but not for ISO 8601.  Odd.  I'll add these.  Thanks.

**Comment by gregsdennis** [comment]
I'm going to use the built-in `.ToString("O")` which is ISO 8601 formatting.  This results in a string that is `1989-04-16T13:11:20.7210000Z`, not what you have, so you'll still want to use custom formatting if you want the TZ encoded.

**Comment by svenskmand** [comment]
> I'm going to use the built-in `.ToString("O")` which is ISO 8601 formatting. This results in a string that is `1989-04-16T13:11:20.7210000Z`, not what you have, so you'll still want to use custom formatting if you want the TZ encoded.

ok, have you released that? I would prefer to use ISO 8601 instead of a custom format.

**Comment by gregsdennis** [comment]
I'm having some build issues due to some new schema tests. Working to resolve those, then I'll release.

**Comment by gregsdennis** [comment]
This is resolved in v13
