### ISSUE TITLE
Move the static JsonSchemaOptions into the JsonSchema instance to allow dynamic instance configuration

### ISSUE THREAD

**Issue by svenskmand** [gregsdennis/Manatee.Json#266]
In the issue https://github.com/gregsdennis/Manatee.Json/issues/262 it was unclear how to configure the error messages when calling `JsonSchema.Validate` and it appeared that the implementation had a bug as the default configuration was to not return any errors. Looking at the `JsonSchema` class it is also not clear that you should configure it by changing a static class `JsonSchemaOptions` instead.

Another benefit of this proposed change is that production and test code do not need to configure the schema validation in one place, namely the static class, but each use case can have its own configuration. See also https://github.com/gregsdennis/Manatee.Json/issues/262 for more details.

**Comment by gregsdennis** [comment]
@svenskmand this will be available in the next major release.  Follow #268 for details.

**Comment by svenskmand** [comment]
Thanks 🙂
