### ISSUE TITLE
Invalid JSON containing multiple objects results in first object

### ISSUE THREAD

**Issue by silkeh** [gregsdennis/Manatee.Json#267]
**Describe the bug**
Parsing (invalid) JSON containing multiple objects (eg `{"a": 1},{"b":2}`) results not in an error, but only in the first object. For example: `{"a": 1},{"b":2}` will result in `{"a": 1}`

**To Reproduce**

Code example:

```C#
var jsonText = @"{""a"": 1},{""b"": 2}";
var json     = JsonValue.Parse(jsonText);
Console.WriteLine(json);
```

Results in:

```json
{"a":1}
```

**Expected behavior**
A `Manatee.Json.JsonSyntaxException` because the JSON is not valid.

**Desktop (please complete the following information):**
 - OS: Linux
- .Net Target: netcoreapp3.1
- .Net Version: 3.1.200
- Manatee.Json version: 12.3.1, master

**Additional context**
Test case for good measure:

```C#
[Test]
public void Issue267_OnlyFirstObjectParsed()
{
	try
	{
		JsonValue.Parse(@"{""a"": 1},{""b"": 2}");
	}
	catch (JsonSyntaxException)
	{
		Assert.Pass();
	}
	Assert.Fail();
}
```

**Comment by gregsdennis** [comment]
Thanks for the report.  I think the best option is to include this as an option.  If you'd like to submit the change as a PR, I'll review it.  Otherwise it may be a bit as my life is rather busy right now.

**Comment by gregsdennis** [comment]
@silkeh I'm attacking all of the open things (that I can), so I've got this covered in #268.

**Comment by silkeh** [comment]
That was fast! Thanks a lot!
