### ISSUE TITLE
JsonSchema.Validate not working as expected

### ISSUE THREAD

**Issue by SanctumPrime** [gregsdennis/Manatee.Json#274]
I'm attempting to create a schema to validate some user submitted Json. At this point I'm just working with a subset of data to learn how this library works. I've written the schema to fail in 2 places based on my test input, but it's coming back as valid instead of not valid.

**My schema:**
```
{
  "properties": {
    "stepTemplates": {
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/fieldCollectionStepTemplate" }
        ]
      }
    }
  },
  "definitions": {
    "fieldCollectionStepTemplate": {
      "allOf": [
        { "$ref": "#/definitions/fieldTemplateBase" }
      ]
    },
    "fieldTemplateBase": {
      "properties": {
        "id": {
          "maxLength": 38,
          "minLength": 38,
          "type": "string"
        },
        "name": {
          "type": "string",
          "minLength": 6
        }
      },
      "required": [ "id", "name" ]
    }
  }
}
```
**My test data:**
```
{
  "$id": "1",
  "$type": "FormEngine.Templates.JsonFormTemplate, FormEngine",
  "stepTemplates": [
    {
      "$id": "2",
      "$type": "FormEngine.Templates.StepTemplates.FieldCollectionStepTemplate, FormEngine",
      "fieldGroupTemplates": [],
      "valid": true,
      "id": "bc8ef3d9-f9e6-4c92-a804-2057c25fda58",
      "name": null",
      "description": null
    }
  ],
  "valid": true
}
```

**My code:**
```
var schemaOptions = new JsonSchemaOptions();
schemaOptions.OutputFormat = SchemaValidationOutputFormat.Detailed;

var schemaText = File.ReadAllText(SchemaFilePath);
var schemaJsonValue = JsonValue.Parse(schemaText);
var schema = new JsonSerializer().Deserialize<JsonSchema>(schemaJsonValue);

var result = schema.Validate(testDataString, schemaOptions);
```

**Expected behavior**
I expect `result.IsValid` to be false and `result.ErrorMessage` to contain a string pointing to the fact that "id" in the test data is too short, and that "name" in the test data can not be null.

What I get is `result.IsValid` is true and `result.ErrorMessage` is null.

I verified the schema and test data using https://www.jsonschemavalidator.net/ which gives the result I expect so I don't believe that the schema I wrote is incorrect in any way. It's probably a configuration that I'm missing and can't find in the documentation. 

Any help would be greatly appreciated!

 - OS: Windows 10
- .Net core 3.1
 - Version 13.0.2

**Comment by gregsdennis** [comment]
Thanks for the report.

What is the value of `testDataString`?  Is this a `string` or a `JsonValue`?  It _should_ be a `JsonValue`.  If it's a string, that string is being implicitly _cast_ into a `JsonValue`, so the validator is processing the schema against a string value.  Since the schema does not specify that the instance must be an object, the instance passes on strings.

Most keywords, like `properties` and `minLength` only work on certain types of instances.  If the instance is not of that type, the keyword is ignored.  Since you're passing a string, `properties` doesn't apply, there are no string-related keywords, and so the instance passes.

If you parse the string into a `JsonValue` first (as you did the schema before deserializing it), it should work as expected.

**Comment by eraffel-MDSol** [comment]
also, don't know if it was a copy/paste issue, but your test data you put here isn't valid json. The name property has a value of `null"` right now with the trailing double quote

**Comment by SanctumPrime** [comment]
Oh wow... I had tried both passing it as a string and JsonValue and was getting the same result. But I was using `new JsonValue(testDataString)` and not `JsonValue.Parse(testDataString)`. That change made it work. I knew it was something small that I was overlooking. Thanks!

**Comment by SanctumPrime** [comment]
Yes, that was a copy/paste issue.
