### ISSUE TITLE
Incorrect data serialization for classes that extends Dictionary class

### ISSUE THREAD

**Issue by 3axap4eHko** [gregsdennis/Manatee.Json#276]
**Describe the bug**
Incorrect data serialization for classes that extends Dictionary class

**To Reproduce**

1. Define a class
```csharp
public class D : Dictionary<string, object>{ }
```
2. Instantiate an object
```csharp
D objectValue = new D
{
    ["property1"] = 20,
    ["property2"] = 30,
};
```
3. Serialize it
```csharp
var serializer = new JsonSerializer();
var jsonValue = serializer.Serialize(objectValue);
```
```csharp
Console.WriteLine(jsonValue); // { }
```

**Expected behavior**
If you replace class `D` to `Dictionary<string, object>` you will see
```csharp
Console.WriteLine(jsonValue.Object.Count); // {"property1":20,"property2":30}
```

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.329]
- .Net Target Fwk 4.8
 - Version 13.0.2

**Comment by gregsdennis** [comment]
The serializer can't make assumptions on how to serialize a type based on the type's inheritance.  If you were to add a property to `D` then serializing the same way a dictionary is serialized would be wrong.

You need to tell the serializer how to handle that class, either by implementing `IJsonSerializable` on the class or by creating and registering an `ISerializer` implementation.
