### ISSUE TITLE
Download loop of draft/2019-09/meta/applicator

### ISSUE THREAD

**Issue by KodWhat** [gregsdennis/Manatee.Json#277]
**Describe the bug**
When using JsonSchemaRegistry.Get() to fetch a schema based on draft 2019-09, the library downloads the schema and fetch the schema's parent schemas.
After downloading 2019-09/schema and 2019-09/meta/core it downloads 2019-09/meta/applicator in a loop, causing the application to freeze and throw a StackOverflowException.

**To Reproduce**
Use JsonSchemaRegistry.Get() with a schema referencing the draft 2019-09

**Expected behavior**
Download 2019-09/meta/applicator once and continue to download other resources

**Screenshots**
![image](https://user-images.githubusercontent.com/1282471/85693347-75924c00-b6d6-11ea-9373-9fa17917d4fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
- .Net Standard 2.0 - .Net Core 3.1.2
 - Version 13.0.2

**Comment by gregsdennis** [comment]
Why are you downloading it? There's a hardcoded copy in the library.

**Comment by KodWhat** [comment]
I only ask the library to get my schema (first line), but it automatically tries to download the draft

**Comment by KodWhat** [comment]
I may have found the issue : My schema was referencing the draft with http instead of https.
While exploring the download code of the library, I found that it tries to match the https only version (MetaSchemas.Draft2019_09.cs) and tries to download the draft if an http url is provided

**Comment by gregsdennis** [comment]
That sounds a likely culprit. JSON Schema migrated to https only a while back for the downloads, but the IDs of the previous drafts are unchanged.

**Comment by KodWhat** [comment]
I can confirm it works once I changed http to https in my schema. I may have found an old Uri and didn't checked it was http.
Wouldn't it be beneficial to other users to check for http and https, even though it is no more the default uri?

**Comment by gregsdennis** [comment]
The registry can't assume that a request for a schema with ID `http://...` is a mistake and automatically correct to `https://...`.  these are IDs, and therefore need to be exact, regardless of any redirection that the site chooses to do for retrieving the resource.

The spec addresses this in saying that the `$id` value is merely a URI identifier and that the validator should not assume that the screens can be found at the indicated location (URI vs URL).

*Trying* to fetch from the indicated location is as far as I'm willing to stretch this.
