### ISSUE TITLE
StackOverflowException when parsing JSON Schema with internal reference

### ISSUE THREAD

**Issue by gkalnytskyi-asx** [gregsdennis/Manatee.Json#278]
**Describe the bug**
Upgrading from Manatee v13.0.1 to v13.0.2 causes JSON schema validation to throw StackOverflowException.

**To Reproduce**
Here is a sample JSON schema document and C# code that illustrates the error

    // test.json
    {
      "$schema": "http://json-schema.org/draft/2019-09/schema#",

      "definitions": {
        "ArrayItem": {
          "type": "object"
        }
      },

      "title": "dataset object",
      "type": "object",
    
      "properties": {
        "Data": {
          "type": "array",
          "items": {
            "$ref": "#definitions/ArrayItem"
          },
          "default": []
        }
      },
      "required": [ "Data" ]
    }

Here is code I used to read and validate schema

    var schemaText = File.ReadAllText("./test.json");
    var jsonSchema = JsonValue.Parse(schemaText);
    var schema = new JsonSerializer().Deserialize<JsonSchema>(jsonSchema);
    
    var validationOptions = new JsonSchemaOptions() { OutputFormat = SchemaValidationOutputFormat.Detailed };
    
    var schemaValidationResult = schema.ValidateSchema(validationOptions);
    Console.WriteLine(schemaValidationResult.IsValid)

In Manatee v13.0.1 (and v13.0.0) this code works and outputs `true`, but when I upgrade to v13.0.2 (without changing anything else) I receive the StackOverflowException.

**Expected behavior**
Schema validation returns `true`.

**Desktop (please complete the following information):**
 - OS: Windows 10 v1803 (Build 17134.1)
- .Net Target: .Net Core 3.1 
 - Version: 13.0.2

**Additional context**
N/A

**Side question**
I cannot figure out why JSON schema with references that use id's instead of paths (`"$id":"#ArrayItem"` ... `"$ref":"#ArrayItem"` vs. `"$ref":"#definitions/ArrayItem"`) (or even just including id for custom types) is reported as invalid by Manatee.

**Comment by gregsdennis** [comment]
Not sure if it's a typo, but `"$ref": "#definitions/ArrayItem"` is not a valid reference.  It should be `"$ref": "#/definitions/ArrayItem"`.

**Comment by gkalnytskyi** [comment]
@gregsdennis , thank you for pointing out the missing "/" to me, I completely missed that. (I'm the same person as @gkalnytskyi-asx). As for the `definitions` I was following https://json-schema.org/understanding-json-schema/structuring.html , but thank you for pointing this out.

I took the updated example you provided and checked the issue again. I can still reproduce it.

**Comment by gregsdennis** [comment]
Looks like the issue is in the deserialization, not validation.  Investigating.

**Comment by gregsdennis** [comment]
The issue isn't with the validator or deserializer.  You have
```
http://json-schema.org/draft/2019-09/schema#
```
as your `$id`.  The correct ID is `https`, and the `#` shouldn't be there.  These are different from the previous drafts, which use `http` and include a `#`.  It should be
```
https://json-schema.org/draft/2019-09/schema
```

Because this is an ID, I can't be tolerant of these things.  That said, json-schema.org has added HTTP-redirection so that if a request is made for the HTTP-non-S version, it will return the correct document.  This produces a recursive loop, though, because the returned document is cached based on its `$id` not the URL that was used to request it.

**Comment by gkalnytskyi-asx** [comment]
Thank you for your investigation!

**Comment by gregsdennis** [comment]
No.  There's already a lot of documentation (think github issue conversations) around the decision to make this change.  Also... I'm on the JSON Schema team.
