### ISSUE TITLE
JSONPath filter only returns a result if the object is an array

### ISSUE THREAD

**Issue by saiphcbk** [gregsdennis/Manatee.Json#31]
Hi, I've recently switched from Newtonsoft.Json to this package as I've found that you have got the best support for JSONPath expressions. 

I have only a small problem in that if I apply a filter expression to a value that is not an array I get no results. This does work in the java and javascript implementations of JSONPath. 

Using the standard book store model i'm trying to get the bicycle object.

This expression return the bicycle object fine: 
`$.store.bicycle`

However with a filter expression it does not:
`$.store.bicycle[?(1==1)]`

if you apply the same filter expression to the book array its works:
`$.store.book[?(1==1)]`

I've created a .netfiddle to highlight my issue [https://dotnetfiddle.net/LpISLu](https://dotnetfiddle.net/LpISLu)

The kind of things i'm trying to achieve is to only return the store if the price of the bicycle is less than 20
`$[?($.store.bicycle.price < 20)]`

**Comment by gregsdennis** [comment]
Hello, and thank you for switching to the lighter side of JSON in .Net!

I understand the issue and I'll get working on it.  However, it seems odd to me that an array operator is being used to iterate value in an object.

**Comment by gregsdennis** [comment]
I see in the article where he mentions the array operator, and he seems to support your usage, but he doesn't give any examples.

Could you post your expected output, please?  For instance, are you looking for just values, or the key/value pair somehow?

**Comment by gregsdennis** [comment]
@saiphcbk, I have your specific example working, but what do you think should happen if the indexed array operator is used?  JSON objects are unordered, so a numeric index doesn't mean much.

**Comment by saiphcbk** [comment]
Hello, thank you for taking a look at this. I guess I've been basing my expectations on the [Jayway JSONPath](https://github.com/jayway/JsonPath) implementation for Java.

with the path as $[?($.store.bicycle.price < 20)] it returns an array with a single object which is the store

[http://jsonpath.herokuapp.com/?path=$[?($.store.bicycle.price%20%3C%2020)]](http://jsonpath.herokuapp.com/?path=$[?($.store.bicycle.price%20%3C%2020)])

**Comment by gregsdennis** [comment]
That makes sense.  It would return the value of the only key in that object.

I've included the changes in the upcoming v5.0.0 release which primarily revamps JsonSchema.  There aren't any breaking changes for JsonPath.

**Comment by gregsdennis** [comment]
@saiphcbk, I'm looking at this again.  It may be the implementation they use, but jsonpath.org looks like it's returning as you expect for the `1==1` condition, but not the `$.store.bicycle.price<20` condition.  I would think that it should return the entire store, as you expect, but wanted to get your thoughts.
