### ISSUE TITLE
Schema validation ‒ UTF-8 is not supported for enums in referenced schemas

### ISSUE THREAD

**Issue by bpiec** [gregsdennis/Manatee.Json#45]
When you reference a schema that contains an enum with Unicode characters and validate your JSON you will get an error on these values.

Consider the following test:
```csharp
[TestMethod]
public void Utf8Supported()
{
    const string fileName = @"path_to\schema1.json";
    Directory.SetCurrentDirectory(System.IO.Path.GetDirectoryName(fileName));

    const string jsonString = "{\"prop1\": \"ændring\", \"prop2\": {\"prop3\": \"ændring\"}}";
    var schema = JsonSchemaFactory.Load(fileName);
    var json = JsonValue.Parse(jsonString);

    var result = schema.Validate(json);
    Assert.IsTrue(result.Valid);
}
```

where `schema1.json` is:
```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "prop1": {
      "enum": [
        "ændring",
        "test"
      ],
      "type": "string"
    },
    "prop2": {
      "$ref": "schema2.json"
    }
  }
}
```

and `schema2.json` is:
```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "prop3": {
      "enum": [
        "ændring",
        "test"
      ],
      "type": "string"
    }
  }
}
```

Currently the result is `false` with error message: `Property: prop2.prop3.value - '"ændring"' does not match the required value`. And if you debug the schema you can see that `prop3` is described like: `{{"prop3":{"enum":["Ă¦ndring","test"],"type":"string"}}}` (notice the replacement for `æ` character).

The simplest solution is to use UTF-8 while downloading (why do you choose to download the data instead of using IO?) the file. So change `new WebClient().DownloadString(uri))` to `new WebClient { Encoding = Encoding.UTF8 }.DownloadString(uri))` in `JsonSchemaOptions.cs` or some more sophisticated way if you want to support more encodings. I don't know what to do with `HttpClient` though (you cannot pass encoding to it).

**Comment by gregsdennis** [comment]
That's an interesting find.  I'll have a look. 

In the meantime, you might try using the Unicode escape sequence `\u00E6` instead of the raw character.

**Comment by bpiec** [comment]
I cannot modify schemas, I just need to ensure that JSONs produced by me are compliant to schemas provided by someone else. And they are too big to modify them anyway.

**Comment by gregsdennis** [comment]
The test passes for me when I remove the `Directory.SetCurrentDirectory()` call:

	[TestMethod]
	[DeploymentItem("Files\\baseSchema.json")]
	[DeploymentItem("Files\\refSchema.json")]
	public void Issue45_Utf8SupportInReferenceSchemaEnums()
	{
		const string fileName = @"baseSchema.json";
		//var directory = System.IO.Path.GetDirectoryName(fileName);
		//Directory.SetCurrentDirectory(directory);

		const string jsonString = "{\"prop1\": \"ændring\", \"prop2\": {\"prop3\": \"ændring\"}}";
		var schema = JsonSchemaFactory.Load(fileName);
		var json = JsonValue.Parse(jsonString);

		var result = schema.Validate(json);
		Assert.IsTrue(result.Valid);
	}

With the `Directory` call it only works if I put the full path to the schema file, but it still works.

I've uploaded the tests (see *ClientTests.cs* file) to branch **bug/issue45**.

**Comment by bpiec** [comment]
It's true, your tests work. But I did some experimenting and found what was the issue.

You saved your schema files with BOM. If you save them in UTF-8 without BOM than the bug exists. I used Notepad++ to change the encoding.

**Comment by gregsdennis** [comment]
Awesome sleuthing!  I didn't even know that was a thing.  I've been able to replicate.

**Comment by gregsdennis** [comment]
This updated test illustrates the problem when the files are saved with the proper encoding:

	[TestMethod]
	[DeploymentItem("Files\\baseSchema.json")]
	[DeploymentItem("Files\\refSchema.json")]
	public void Issue45b_Utf8SupportInReferenceSchemaEnums()
	{
		const string fileName = @"baseSchema.json";

		const string jsonString = "{\"prop1\": \"ændring\", \"prop2\": {\"prop3\": \"ændring\"}}";
		var schema = JsonSchemaFactory.Load(fileName);
		var json = JsonValue.Parse(jsonString);

		var result = schema.Validate(json);

		Console.WriteLine(schema.ToJson(null));
		var refSchema = ((JsonSchemaReference)((JsonSchema)schema).Properties["prop2"].Type).Resolved;
		Console.WriteLine(refSchema.ToJson(null));
		Console.WriteLine(json);
		foreach (var error in result.Errors)
		{
			Console.WriteLine(error);
		}

		Assert.IsTrue(result.Valid);
	}

**Comment by gregsdennis** [comment]
For reference, here's an explanation of the problem:

http://stackoverflow.com/a/2223926/878701

**Comment by bpiec** [comment]
Do you have any plan on fixing this? My validation component outputs multiple errors now :(

**Comment by gregsdennis** [comment]
My apologies. I thought I had published a fix.  I'll pick this up again and see where it is.

**Comment by gregsdennis** [comment]
I've resolved it for the numbered .Net versions.  The portable and core versions will need to use `HttpClient` as they don't have `WebClient`.  But [according to Jon Skeet](http://stackoverflow.com/a/11018883/878701) it should detect encoding automatically based on headers.  I'm not sure how that works for local files.  I'll post a question.

In the meantime, I'll publish as is.  Look for version 5.2.0.

**Comment by bpiec** [comment]
Works like a charm, thanks!

**Comment by gregsdennis** [comment]
Glad to hear it.  Closing.
