### ISSUE TITLE
Issue parsing strings that end with a backslash.

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Json#47]
As an example

    "some text\\"

should parse to a `JsonValue` with the string value of

    some text

But it seems that the `\"` is taking precedence over the `\\` causing the end of the string to not be found.

**Comment by gregsdennis** [comment]
@nvaghari here is where I'll track this issue.

**Comment by nvaghari** [comment]
@gregsdennis thank you a lot

**Comment by gregsdennis** [comment]
Bug was in the `StringParser` class.  The loop kept track of when it found an escape character (`\`) but didn't clear the flag on the next character, so it thought the ending double-quote was supposed to be escaped.

**Comment by gregsdennis** [comment]
@nvaghari, please download Manatee.Json v5.2.1 when it becomes available.
