### ISSUE TITLE
Deserializing schema with required properties but empty property collection throws null-ref.

### ISSUE THREAD

**Issue by vector-man** [gregsdennis/Manatee.Json#49]
Hi,

I'm getting an ArgumentNullException when using JsonSchemaFactory.Load(fileName).

Parameter name: source

Some of my stack trace:
       
           at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
           at Manatee.Json.Schema.JsonSchema.FromJson(JsonValue json, JsonSerializer serializer) in D:\temp\532b9b0\Manatee.Json\Schema\JsonSchema.cs:line 610
           at Manatee.Json.Schema.JsonSchemaFactory.FromJson(JsonValue json) in D:\temp\532b9b0\Manatee.Json\Schema\JsonSchemaFactory.cs:line 106
           at Manatee.Json.Schema.JsonSchema.FromJson(JsonValue json, JsonSerializer serializer) in D:\temp\532b9b0\Manatee.Json\Schema\JsonSchema.cs:line 624
           at Manatee.Json.Schema.JsonSchemaFactory.FromJson(JsonValue json) in D:\temp\532b9b0\Manatee.Json\Schema\JsonSchemaFactory.cs:line 106
           at Manatee.Json.Schema.JsonSchemaFactory.Load(String path) in D:\temp\532b9b0\Manatee.Json\Schema\JsonSchemaFactory.cs:line 78

I cannot show my schema due to it being a commercial product, but I'll see if I can write up similar a failing schema.

**Comment by gregsdennis** [comment]
Thanks for the report. I will investigate.

Is this every time, or just with certain data?

**Comment by vector-man** [comment]
No problem! Just with certain data. It's  somehow linked to the combination of allOf and required. I'll keep you updated.

**Comment by vector-man** [comment]
It also looks like it is trying to look up a level when searching for external schema files.
For example:

Two files, a.json and b.json are in the folder Game
 If a.json references b.json like this: { "$ref": "b.json#" },

I get an error that the file cannot be found (and the path in the exception is pointing to Debug folder, not Debug/Game

I have to change it to:
 { "$ref": "Game/a.json#" },

**Comment by gregsdennis** [comment]
If you can get a concise example of the schema load issue, that'll help a lot.

Got the file reference one, I'll need to reconcile that with other issues I've fixed, but it seems to be an issue with the system looking in the runtime directory.  Please create a separate issue for that.

**Comment by vector-man** [comment]
{
          "title": "JSON schema for Something",
          "$schema": "http://json-schema.org/draft-04/schema#",
          "definitions": {
            "something": {
              "type": "object",
              "required": [ "name" ],
              "allOf": [
                {
                  "properties": {
                    "name": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          },
          "type": "array",
          "description": "An array of somethings.",
          "items": {
            "$ref": "#/definitions/something"
          }
        } 

Removing "required" or "allOf" will cause it to work.

**Comment by gregsdennis** [comment]
Okay... This schema *is* built a little weird, but just the same, the system should be able to handle it.

The system expects that if `required` is present then `properties` should also be present, but that's not the case with this schema.

This should be an easy enough fix.

**Comment by gregsdennis** [comment]
This one is resolved.  I'll take a look at the other one.  Once I have that handled, I'll publish an update to Nuget.
