### ISSUE TITLE
Vague/incorrect schema validation error messages.

### ISSUE THREAD

**Issue by vector-man** [gregsdennis/Manatee.Json#55]
Hi, I'm not sure if this a new bug, but I'm getting vague (or incorrect?) error messages with the latest release:

            var schema = JsonSchemaRegistry.Get(schemaPath);
            SchemaValidationResults results = null;
            results = _schema.Validate(@"{}"); // Or some other schema.
            foreach (SchemaValidationError error in results.Errors)
            {
                _logger.Error(error);
            }

Test schema:

    {
      "$schema": "http://json-schema.org/draft-04/schema",
      "title": "JSON Schema for Universally Unique Identifiers (UUIDs).",
      "type": "object",
      "properties": {
      "uuid": {
      "description": "A universally unique identifier (UUID).",
      "type": "string",
      "pattern": "^([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})|[a-f0-9]{32}$
    }

Result:

    "Expected String; Actual String."
Edit:

Looks like it is only a problem when passing a string to Validate instead of JsonValue.Parse() (I may be wrong, though)

Edit 2:
Looks like it will also cause a valid schema to fail, unless you pass a JsonObject into Validate

**Comment by gregsdennis** [comment]
Thanks for the report.  I'll have a look.

**Comment by gregsdennis** [comment]
Your schema JSON looks incomplete.  Can you verify, please?

**Comment by gregsdennis** [comment]
I've replicated the problem.  Digging in...

**Comment by gregsdennis** [comment]
Okay, there are a few issues.

First, yes, there is a bug in the error messaging. It should report `Expected: object; Actual: String` because the schema expects an object at the root. I've fixed that and will upload shortly.

Second, when you call validate, you have to pass in a `JsonValue`.  You're getting the error because you're using in a string, which gets converted to a JSON string.  Something like this should work as I think you expect:

    var results = schema.Validate(new JsonObject());

**Comment by gregsdennis** [comment]
Please see branch **bug/issue-55**.

**Comment by gregsdennis** [comment]
@vector-man, I've published v6.0.1 with the new messaging.  I'd like to confirm that this is what you're looking for, please.

**Comment by vector-man** [comment]
Thanks. I'll check it out later today!

**Comment by vector-man** [comment]
Looks good now! Thanks!

**Comment by gregsdennis** [comment]
Thanks for the confirmation.  Closing this.
