### ISSUE TITLE
Schema Validation reference schema 

### ISSUE THREAD

**Issue by mecowhy** [gregsdennis/Manatee.Json#58]
Consider following test:

	[TestMethod]
	[DeploymentItem(@"Files\IssueRefCore.json", "Files")]
	[DeploymentItem(@"Files\IssueRefChild.json", "Files")]
	public void UriReferenceSchemaTest()
	{
		const string coreSchemaUri = "http://example.org/IssueRefCore.json";
		const string childSchemaUri = "http://example.org/IssueRefChild.json";

		string coreSchemaPath = System.IO.Path.Combine(TestContext.TestDeploymentDir, @"Files\IssueRefCore.json");
		string childSchemaPath = System.IO.Path.Combine(TestContext.TestDeploymentDir, @"Files\IssueRefChild.json");

		var coreSchemaText = string.Empty;
		var childSchemaText = string.Empty;

		using (TextReader reader = File.OpenText(coreSchemaPath))
		{
			coreSchemaText = reader.ReadToEnd();
		}

		using (TextReader reader = File.OpenText(childSchemaPath))
		{
			childSchemaText = reader.ReadToEnd();
		}

		var requestedUris = new List<string>();
		JsonSchemaOptions.Download = (uri) => 
		{
			requestedUris.Add(uri);
			switch(uri)
			{
				case coreSchemaUri:
					return coreSchemaText;
					
				case childSchemaUri:
					return childSchemaText;
			}
			return coreSchemaText;
		};
		var schema = JsonSchemaRegistry.Get(childSchemaUri);

		var testJson = new JsonObject();
		testJson["myProperty"] = "http://example.org/";
		   
		var result = schema.Validate(testJson);
		
		Assert.IsTrue(result.Valid);
		Assert.AreEqual(requestedUris[0], childSchemaUri);
		Assert.AreEqual(requestedUris[1], coreSchemaUri);
	}

Where:

Files\IssueRefCore.json is:

	{
	  "$schema": "http://json-schema.org/draft-04/schema#",
	  "id": "http://example.org/IssueRefCore#",
	  "title": "Core Schema",
	  "description": "",
	  "definitions": {
		"myProperty": {
		  "type": "string",
		  "format": "uri"
		}
	  }
	}

and Files\IssueRefChild.json is:

	{
	  "$schema": "http://json-schema.org/draft-04/schema#",
	  "id": "http://example.org/IssueRefChild#",
	  "title": "Child Schema",
	  "description": "",
	  "properties": {
		"myProperty": { "$ref": "IssueRefCore.json#/definitions/myProperty" }
	  },
	   "required" : [ "myProperty" ]
	}

this test fails.

    "myProperty": { "$ref": "IssueRefCore.json#/definitions/myProperty" }

should download http://example.org/IssueRefCore.json and navigate to /definitions/myProperty but it tries to get http://example.org/IssueRefChild.json again instead.

**Comment by mecowhy** [comment]
[ReferenceSchemaTest.zip](https://github.com/gregsdennis/Manatee.Json/files/993017/ReferenceSchemaTest.zip)

**Comment by gregsdennis** [comment]
Confirmed the issue.  There is a problem in URI resolution in `JsonSchemaReference.Resolve()`.

@vector-man, would you mind taking a look into this?  I think it was introduced with (or at least exposed by) your changes.

**Comment by vector-man** [comment]
@gregsdennis I think I fixed it. I'm going to look it over and push it once I think it looks good.

**Comment by vector-man** [comment]
Was Issue45a_Utf8SupportInReferenceSchemaEnums always failing? Just wanted to confirm before I commit.

**Comment by gregsdennis** [comment]
It passes in the unmodified code.

**Comment by vector-man** [comment]
Oh, looks like the problem is the path is hardcoded to  folder on your PC. After changing that, everything passes.

**Comment by gregsdennis** [comment]
@vector-man Looks good.  Thanks.

@mecowhy I'll have an update posted tonight.  Look for v6.0.2.

**Comment by vector-man** [comment]
@gregsdennis No problem!

**Comment by mecowhy** [comment]
@gregsdennis @vector-man ,
thanks for quick response.

**Comment by gregsdennis** [comment]
v6.0.2 is now available on Nuget.

**Comment by vector-man** [comment]
Looks like there is still a problem when IDs are under different domains. I'm going to think about a better way to handle this and get back to you.

**Comment by vector-man** [comment]
@gregsdennis The resolve issue seems to be a little more difficult to completely solve than I thought. I'll try to find the time to fix it, but I'm not sure of an exact date on when it will be done

**Comment by gregsdennis** [comment]
That's fine.  I'll dig into it as I can as well.  Can you describe a bit more or provide an example.

**Comment by vector-man** [comment]
Upon further review of the JSON Schema spec, what I was concerned about may not be a problem afterall. It was related to the way URIs in IDs were handled in Resolve (the composed address with popped allIDs in #58). I'm going to look over it closely later to make sure everything is okay, but I have not found a specific issue yet. If you find any issue, please don't hesitate to contact me!

**Comment by gregsdennis** [comment]
Sounds good.  Thanks.

**Comment by gregsdennis** [comment]
@vector-man don't know if this is a result of the changes, but I've updated the schema repo reference and it looks like we have some reference errors.  See branch **bug/schema-suite-failures**.

**Comment by vector-man** [comment]
It may be. The change I did basically ignored the complete address (only grabbing the initial part)

I am working on a fix. I'll push it when I finish.

**Comment by vector-man** [comment]
Looks like the test suite is looking for a file:  \remotes\nodenode . I did make a mistake in the Resolve logic. The new version does result in the same testSuite error though

I'm thinking this is better (but still failing, of course)
    
    private JsonValue Resolve(JsonValue root)
    {
        var referenceParts = Reference.Split(new[] { '#' }, StringSplitOptions.None);
        var address = referenceParts[0];
        var path = referenceParts.Length > 1 ? referenceParts[1] : string.Empty;
        var jValue = root;
        if (!address.IsNullOrWhiteSpace())
        {
            Uri uri;
            var search = JsonPathWith.Search("id");
            var allIds = new Stack<string>(search.Evaluate(root ?? new JsonObject()).Select(jv => jv.String));
            while (allIds.Any() && !Uri.TryCreate(address, UriKind.Absolute, out uri))
            {
                address = allIds.Pop() + address;
            }

            Uri absolute;

            if (!Uri.TryCreate(address, UriKind.Absolute, out absolute))
            {
                if (DocumentPath != null)
                {
                    DocumentPath = new Uri(DocumentPath.GetParentUri(), address);
                }
            }
            else
            {
                var parts = absolute.ToString().Split(new[] { '#' }, StringSplitOptions.None);
                DocumentPath = new Uri(parts[0]);

                if (parts.Count() == 2)
                {
                    DocumentPath = new Uri(DocumentPath.GetParentUri(), parts[1]);
                }
            }

            jValue = JsonSchemaRegistry.Get(DocumentPath?.ToString()).ToJson(null);
        }
        if (jValue == null) return root;
        if (jValue == _rootJson) throw new ArgumentException("Cannot use a root reference as the base schema.");

        Resolved = ResolveLocalReference(jValue, path, DocumentPath);
        return jValue;
    }

. The test file that is causing it is: ref.json. I'm going to look at it more later.

**Comment by gregsdennis** [comment]
The tests that are failing are the *Recursive references between schemas* tests in *ref.json*.  What's interesting about these tests is that the schema has references in the form `{"$ref" : "node"}`, which doesn't follow the URI format we see in the other tests (file, URL, or schema-internal); it's just a single name.

From [section 8 of the spec](http://json-schema.org/latest/json-schema-core.html#rfc.section.8):

>An object schema with a "$ref" property MUST be interpreted as a "$ref" reference. The value of the "$ref" property MUST be a URI Reference. **Resolved against the current URI base**, it identifies the URI of a schema to use. All other properties in a "$ref" object MUST be ignored.

This means that `{"$ref" : "node"}` should start with the schema's location (`http://localhost:1234/tree`), take the base (`http://localhost:1234`) and append the reference to the path to get `http://localhost:1234/node`.  This can get quite complex if we're looking at nested/progressive namespaces.

The wrinkle in this is that the root is passed in only as JSON, not as a schema, so we can't tell what the ID is without either making assumptions about the JSON (specifically that it represents a schema) or deserializing it (which would be inefficient given that we serialized it to pass it in to begin with).

---

All of that to say this:  Maybe the `Validate()` method needs to be updated to take a schema rather than a JSON value.

Alternatively, an additional `currentPath` parameter could be added to `Validate()`.

Thoughts?

**Comment by vector-man** [comment]
Do you think that setting the Schema's initial DocumentPath and then modifying Validate would also work for this?

**Comment by gregsdennis** [comment]
I'm exploring that locally.  I set the document path to the ID during deserialization.  I have an idea about the validate: the issue is around the path stack.

**Comment by gregsdennis** [comment]
@vector-man I've uploaded the changes to initialize the schema's `DocumentPath` during deserialization.

**Comment by gregsdennis** [comment]
I've added #63 to cover the only remaining failure (that I can see) from this.

**Comment by gregsdennis** [comment]
@mecowhy, please see v6.0.3.  I believe this will resolve your issue.

**Comment by mecowhy** [comment]
I checked it with v6.0.2 and it passed my tests, now updated to v6.0.3 and tests still pass.

**Comment by gregsdennis** [comment]
Yes, I believe it should pass, as the value is a valid URI.
