### ISSUE TITLE
Schema Validation: String Format=Uri

### ISSUE THREAD

**Issue by mecowhy** [gregsdennis/Manatee.Json#62]
Changing the test value in `ValidateReturnsErrorOnInvalidUriFormat` to `test` that also isn't a valid uri causes the test to fail.

Test after change:

```	
public void ValidateReturnsErrorOnInvalidUriFormat()
{
	var schema = new JsonSchema {Type = JsonSchemaTypeDefinition.String, Format = StringFormat.Uri};
	var json = (JsonValue) "test";
	var results = schema.Validate(json);

	Assert.AreNotEqual(0, results.Errors.Count());
	Assert.AreEqual(false, results.Valid);
}
```

**Comment by gregsdennis** [comment]
According to the JSON Schema Test Suite, `test` *is* a valid URI (which is correct).  It's a relative URI.

This is precisely the problem we continue to deal with in #58.

**Comment by gregsdennis** [comment]
@mecowhy is the test code you show above intended to pass or fail?

**Comment by mecowhy** [comment]
I think it should fail, even if it's relative reference shouldn't it contain "//" or dot-segment "./" at the begining ? https://tools.ietf.org/html/rfc3986#section-4.2

**Comment by gregsdennis** [comment]
The test that was giving us problems on the other issue had a reference like `folder/`.  This is a folder reference.  Without the slash, it is a file reference (at least that's how I'm interpreting it).

That said, `test` validates as a URI.
