### ISSUE TITLE
JSON string with name of primitive schema type should fail validation

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Json#63]
Given the schema `{ "type" : "array" }` the value `"string"` should fail, but doesn't.

**Comment by gregsdennis** [comment]
working! will merge and publish soon.

**Comment by gregsdennis** [comment]
@vector-man, I think this resolves the issues we've seen with the schema referencing.  See branch **bug/schema-suite-failures**.

**Comment by gregsdennis** [comment]
v6.0.3 released

**Comment by vector-man** [comment]
@gregsdennis Great to hear!
