### ISSUE TITLE
migration to 2017

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Json#65]
Need to migrate these projects to VS2017.  The stickler is the core version.  2017 implemented these projects differently than 2015.

**Comment by gregsdennis** [comment]
Successfully created a single, multi-targeted project for netstandard1.3 and net46.  The downside to this is that support for anything lower than 4.6 is dropped.

See branch **task/2017-migration**

This is a major change.

**Comment by gregsdennis** [comment]
This is a precursor to #61.

**Comment by gregsdennis** [comment]
@mecowhy @vector-man @bpiec @damon-kwok @saiphcbk 

Since you are the only users of this library that I know about, you get a say in this.

I'm planning on releasing this version.  What is your current usage, framework-wise?  Does anyone need a framework lower than 4.6 to support current projects?  Would moving to 4.6+ or .Net Core in the future be an issue for anyone?

**Comment by bpiec** [comment]
I don't work for that company anymore but they were using 4.6+ so that's ok.

**Comment by vector-man** [comment]
Hi. I know this is closed, but I just wanted to add that the project I'm working on is targeting the latest .NET framework, so as long as it will work with that, no problem!
