### ISSUE TITLE
Performance enhancements around serialization

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Json#9]
I ran some performance tests comparing Manatee.Json to Newtonsoft, and Manatee lost. Badly.

There are opportunities for making Manatee.Json (much) faster. This task is for finding and implementing those improvements.

As of publishing the parsing improvements:
- Newtonsoft beats Manatee in tests with 500+ iterations.
- Manatee prevails with less than 500 (singles are best).

It seems that Newtonsoft has some sort of caching mechanism that helps with rapid repeated serialization.

At 10K iterations, Manatee takes 10x the time of Newtonsoft. (This is down from ~50x.) The reverse is true for single iterations (Manatee takes 1/10 the time of Newtonsoft).

**Comment by gregsdennis** [comment]
A [recent blog post comparing serializers](The Definitive Serialization Performance Guide - http://wp.me/p7FuSd-4W) may have identified part of the problem.

**Comment by gregsdennis** [comment]
A big part of the slowness is multiple iterations of the serialization cache.  In the `Referencing Serializer`...

	1	public JsonValue Serialize<T>(T obj, JsonSerializer serializer)
	2	{
	3		SerializationPair pair;
	4		if (serializer.SerializationMap.Contains(obj))
	5		{
	6			var guid = serializer.SerializationMap.GetKey(obj);
	7			pair = serializer.SerializationMap[guid];
	8			pair.UsageCount++;
	9			return new JsonObject {{Constants.RefKey, guid.ToString()}};
	10		}
	11		if (_innerSerializer.ShouldMaintainReferences)
	12		{
	13			var guid = Guid.NewGuid();
	14			pair = new SerializationPair {Object = obj};
	15			serializer.SerializationMap.Add(guid, pair);
	16			pair.Json = _innerSerializer.Serialize(obj, serializer);
	17			if (pair.UsageCount != 0)
	18				pair.Json.Object.Add(Constants.DefKey, guid.ToString());
	19			return pair.Json;
	20		}
	21		return _innerSerializer.Serialize(obj, serializer);
	22	}

There are separate enumerations of the cache on lines 4 and 6, then a hash-lookup is performed on line 7.

**Comment by gregsdennis** [comment]
See branch **task/issue-9-serialization-performance**.

Reimported my performance tests.  No definitive difference was gained from these changes.

**Comment by sixlettervariables** [comment]
I'm evaluating this project for one of our products at work and was interested in the performance differences. I played around a bit with just the Parsing side of the house, and managed to get it to here:
```
BenchmarkDotNet=v0.10.11, OS=Windows 7 SP1 (6.1.7601.0)
Processor=Intel Xeon CPU E5-2620 v3 2.40GHzIntel Xeon CPU E5-2620 v3 2.40GHz, ProcessorCount=24
Frequency=2338369 Hz, Resolution=427.6485 ns, Timer=TSC
  [Host]     : .NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2114.0
  DefaultJob : .NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2114.0


      Method |     Mean |     Error |   StdDev |     Gen 0 |    Gen 1 |    Gen 2 | Allocated |
------------ |---------:|----------:|---------:|----------:|---------:|---------:|----------:|
     JsonNET | 36.36 ms | 0.9523 ms | 2.808 ms | 1062.5000 | 437.5000 | 125.0000 |   5.76 MB |
 ManateeJson | 62.78 ms | 1.2530 ms | 2.929 ms | 4062.5000 | 625.0000 | 187.5000 |  23.54 MB |
   MyManatee | 40.03 ms | 1.0915 ms | 3.218 ms | 1375.0000 | 437.5000 | 125.0000 |   7.87 MB |
```

This was on a loop decoding a ~800 KB JSON file stream. Any interest in these generic performance contributions?

**Comment by gregsdennis** [comment]
Sure, create a PR, and I'll go through it.  I've been tied up with schema and other features lately, so I haven't had a lot of time to get to the performance side of things.  Thank you.

**Comment by sixlettervariables** [comment]
Well we're evaluating it for Schema work, so I'm glad to hear that! I'll work on a (non-mergeable) PR to give you an idea of what it looks like to achieve that performance. I can then break it apart by specific areas/means of improvement, because there is a definite loss in readability in some areas in order to support the improvements.

**Comment by gregsdennis** [comment]
For comparison, I ran my own tests (anecdotally) on parsing random data generated from https://www.json-generator.com/.  The data was 676 MB.  The test was 1000 parsing passes.

The current method took about 1m15s.
The new method took just about 30s.

A nice improvement, indeed!
